### ISSUE TITLE
gaming.youtube.comに対応する

### ISSUE THREAD

**Issue by clngn** [clngn/vtuber-comment-extension#1]

**Comment by clngn** [comment]
対応した https://github.com/clngn/vtuber-comment-extension/releases/tag/v0.3

**Comment by volksliednacht** [comment]
締めた後で申し訳ないのですが、現在の最新バージョンver0.5でもgaming.youtubeに対応しているでしょうか。
同じバージョンでもyoutubeでは登録したコメントが通知されたのですが、gaming.youtubeでは通知されませんでした。
他の人が使えているのであればこちらの設定がダメなだけだとは思いますが、確認お願いできますか？

**Comment by clngn** [comment]
すみません、配信チャンネル名の追加でデグレってしまっていたようです
直します〜〜〜:bow:

**Comment by clngn** [comment]
修正しました！ https://github.com/clngn/vtuber-comment-extension/releases/tag/v0.6

**Comment by volksliednacht** [comment]
gaming.youtube.comの内容なので、再度こちらに。
youtubeの場合はURLが「https://www.youtube.com/channel/(チャンネルURL)/live」でも「https://www.youtube.com/watch?v=xxxxxxxxx」でもコメントの通知が出ます。
ところがgaming.youtube.comの場合、「https://gaming.youtube.com/watch?v=xxxxxxxx」ではコメントの通知が出ますが、「https://gaming.youtube.com/channel/(チャンネルURL)/live」では通知が出ません。
おそらく「"https://gaming.youtube.com/watch*"」となっているから取得できてないと思っていますが、修正予定などありますか？

**Comment by clngn** [comment]
すみません、確認して修正します〜:bow:
