### ISSUE TITLE
ポップアップ通知が表示されない

### ISSUE THREAD

**Issue by volksliednacht** [clngn/vtuber-comment-extension#14]
2019年8月末ごろから登録している名前の人がポップアップ通知されない現象が起きています。
ただ、「通知テスト」を押した時には表示されています。
OSの通知設定もChromeは通知オンにしていますし、
Chrome設定の通知に関しても「https://www.youtube.com」の『通知』、『ポップアップとリダイレクト』を許可にしています。
原因は分かるでしょうか？

**Comment by clngn** [comment]
修正バージョンをリリースしました！
こちらで直ったかと思います:bow:
https://github.com/clngn/vtuber-comment-extension/releases/tag/v0.9

また何かありましたらIssueいただけたら幸いです:pray:
