### ISSUE TITLE
テキストが繰り返されてしまう場合がある

### ISSUE THREAD

**Issue by gigacee** [clngn/vtuber-comment-extension#18]
![みんなよう見とる_テキストが繰り返される場合がある](https://user-images.githubusercontent.com/5264444/90013632-99d6d600-dce0-11ea-87f3-d10d5fb92aaa.png)

発生条件は不明。同じ配信・同じ発言者でも、発生したりしなかったりします。

**Comment by pirocot** [comment]
@gigacee だいぶ昔の投稿ですみません😜

@clngn ご無沙汰してます。今年もよろしくおねがいします🎉

コメントに絵文字とテキストが混在するケースにおいて、Youtubeがテキストノードを複数に分けています。恐らくですが表示上、ピッチなどの見栄えを細かく調整するためだと考えられます。

※顔文字等の記号については実例のスクショを紛失してしまったのですが、ある時期のみ同様の現象が見られました。

これに対して #10 でid="message"の全ての子ノードのループ内で [Text.wholeText](https://developer.mozilla.org/en-US/docs/Web/API/Text/wholeText) を使用するよう変更したため、テキストノードが現れる度に隣接する全てのテキストノードが毎回重複して結合されています。

対策ですが、対象がテキストノードであることは確定しているため textContent に置き換えれば良いと思います。一応3ヶ月程度動かしてみて目立った問題は起きていません。

後ほどPRしますね。

https://github.com/clngn/vtuber-comment-extension/blob/bfceab42a3f079873cf439eabc7627b76631b73e/src/watch.js#L28-L31

以下重複発生時の例です。

![2022-01-17_20h20_03](https://user-images.githubusercontent.com/1260365/149760717-99700be7-42fd-45b1-a864-3fa1dad14058.png)

![2022-01-17_20h20_37](https://user-images.githubusercontent.com/1260365/149760732-05128d54-e1ef-464d-a710-7a522de0da9a.png)

**Comment by clngn** [comment]
@pirocot 
検証、及びPRまでありがとうございます……！
取り込ませていただきます〜！

今年もよろしくお願いします🐯
